name:           Liliya's Akhtyamova Blog

description:    "The personal site of Liliya Akhtyamova, data scientist. Where I write about code, data science problems, faith and life. Views expressed are my own."

url:            http://github.com/data

gems:
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: compressed

lsi:            false

exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]

permalink:      /writing/:title

markdown_ext:   markdown,mkd,mkdn,md

collections:
  case-studies:
    output: true
    permalink: /:collection/:path/
    defaults:
      layouts: casestudy
